wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1675498548.870507
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 1
      - 23
      4: 3.8.10
      5: 0.13.9
      6: 4.26.0
      8:
      - 1
      - 5
adap_kl_ctrl:
  desc: null
  value: true
batch_size:
  desc: null
  value: 2
cliprange:
  desc: null
  value: 0.2
cliprange_value:
  desc: null
  value: 0.2
forward_batch_size:
  desc: null
  value: 1
gamma:
  desc: null
  value: 1
horizon:
  desc: null
  value: 10000
init_kl_coef:
  desc: null
  value: 0.2
lam:
  desc: null
  value: 0.95
learning_rate:
  desc: null
  value: 1.0e-05
log_with:
  desc: null
  value: wandb
model_name:
  desc: null
  value: .././02-finetune/model/custom-finetuned
ppo_epochs:
  desc: null
  value: 4
remove_unused_columns:
  desc: null
  value: false
steps:
  desc: null
  value: 20000
target:
  desc: null
  value: 6
total_ppo_epochs:
  desc: null
  value: 10000
tracker_project_name:
  desc: null
  value: trl
vf_coef:
  desc: null
  value: 0.1
